### ISSUE TITLE
معماری کلین یا  ماژولار

### ISSUE THREAD

**Issue by ghost** [abbas-oveissi/AndroidModularization#1]
سلام

به نظر شما استفاده از معماری کلین  بهتر هستش یا ماژولار با  این که  کلین تقریبا چیزی  شبه  ماژولار هستش ولی میخوام بدونم کدوم روش  رو شما  پیشنهاد   میدید

توی ماژولار بهتره  mvp  رو توی هر ماژولی مثل  داگر بنویسیم ؟

**Comment by abbas-oveissi** [comment]
<div dir="rtl">
سلام

بنظرم کلین و ماژولار چیزی در یک سطح نیستند که با هم مقایسه بشن. این ریپو در مورد این هست که چطوری میشه  توی اندروید، یه اپ رو به چند ماژول خُرد کرد. صحبتی در مورد اینکه mvp ، mvvm  یا clean رو استفاده میکنید نمیکنه، این موضوع یه بحث جداس که میشه توی پروژه ماژولار هرکدوم رو استفاده  کرد.

من کلا پروژه چه یه ماژول باشه و چه مثل این ریپو چند ماژول باشه، پکیج‌هامو براساس feature دسته‌بندی میکنم. یعنی فرق نمیکنه mvvm و mvp، هرچی فایل مرتبط با یه feature هست (مثلا feature رو میشه یه اسکرین از اپ فرض کرد) رو توی یه پکیج میذارم. در نتیجه جواب سوالتون مثبت هست.

</div>
